#!/usr/bin/env python

def set_options(opt):
	pass


def configure(conf):
	conf.check_cfg(package='speex', uselib_store='SPEEX', args='--cflags --libs', mandatory=1)
	conf.check_cfg(package='speexdsp', uselib_store='SPEEXDSP', args='--cflags --libs', mandatory=1)


def build(bld):
	obj = bld(
		features = ['cxx', 'cstaticlib'],
		uselib = 'BOOST BUILDMODE STRICT',
		target = 'ion_audio_common',
		name = 'ion_audio_common',
		uselib_local = 'ion_common jsoncpp',
		export_incdirs = '.',
		includes = '.'
	)
	obj.find_sources_in_dirs('.')

