#!/usr/bin/env python
import os


def set_options(opt):
	pass


def configure(conf):
	conf.check_cfg(package='alsa', uselib_store='ALSA', args='--cflags --libs')
	conf.check_cfg(package='speex', uselib_store='SPEEX', args='--cflags --libs')
	conf.check_cfg(package='speexdsp', uselib_store='SPEEXDSP', args='--cflags --libs')
	conf.env['CPPPATH_MPG123'] = os.path.join(os.getcwd(), "extern/mpg123-1.12.3/src/libmpg123")
	conf.env['LIBPATH_MPG123'] = os.path.join(os.getcwd(), "extern/mpg123-1.12.3/src/libmpg123/.libs")
	conf.env['LIB_MPG123'] = 'mpg123'
	conf.env['CPPPATH_ADPLUG'] = os.path.join(os.getcwd(), "extern/adplug-2.2.1/src")
	conf.env['LIBPATH_ADPLUG'] = os.path.join(os.getcwd(), "extern/adplug-2.2.1/src/.libs")
	conf.env['LIB_ADPLUG'] = 'adplug'


def build(bld):
	obj = bld(
		features = ['cxx', 'cstaticlib'],
		uselib = 'BOOST_THREAD ALSA MPG123 SPEEXDSP SPEEX BOOST BUILDMODE STRICT',
		target = 'ionplayer_backend',
		name = 'ionplayer_backend',
		uselib_local = 'ionplayer_common dumb jsoncpp',
		includes = '.'
	)
	obj.find_sources_in_dirs('.')
	obj.source.remove('./main.cpp')

	obj = bld(
		features = ['cxx', 'cprogram'],
		uselib = 'BUILDMODE STRICT',
		target = 'backend',
		uselib_local = 'ionplayer_backend ionplayer_common',
		includes = '.',
		source = 'main.cpp'
	)

