#!/usr/bin/env python

def set_options(opt):
	opt.tool_options('qt4')


def configure(conf):
	conf.check_tool('qt4')


def build(bld):
	obj = bld(
		features = ['cxx', 'cstaticlib'],
		uselib = 'QTCORE QTGUI BUILDMODE STRICT',
		target = 'ionplayer_frontend',
		name = 'ionplayer_frontend',
		uselib_local = 'ionplayer_common',
		includes = '.'
	)
	obj.find_sources_in_dirs('.')
	obj.source.remove('./main.cpp')

	obj = bld(
		features = ['cxx', 'cprogram'],
		uselib = 'QTCORE QTGUI BUILDMODE STRICT',
		target = 'frontend',
		uselib_local = 'ionplayer_frontend ionplayer_common',
		includes = '.',
		source = 'main.cpp'
	)

