#!/usr/bin/env python

def set_options(opt):
	opt.tool_options('qt4')


def configure(conf):
	conf.check_tool('qt4')


def build(bld):
	obj = bld(
		features = ['cxx', 'cprogram'],
		uselib = 'QTCORE BUILDMODE STRICT',
		target = 'scanner_test',
		uselib_local = 'ionplayer_common',
		includes = '.'
	)
	obj.find_sources_in_dirs('.')

